name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux-build:
    name: Build and Test

    runs-on: ubuntu-latest
    steps:

    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Install build dependencies for simview
      run: |
        sudo apt-get update -qq
        sudo apt install -y libunwind-dev
        sudo apt install -y \
          build-essential cmake ninja-build \
          g++ default-jre \
          google-perftools \
          python3 python3-dev python3-orderedmultidict python3-psutil \
          libgoogle-perftools-dev \
          uuid-dev

    - name: Checkout simview
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: build-cache

    - name: Configure shell
      run: |
        echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV

    - name: Show shell configuration
      run: |
        env

    - name: Build
      run: |
        cmake -B build -GNinja .
        ninja -C build

    - name: Test
      run: |
        ninja -C build test

  CodeFormatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo apt-get install clang-format

    - name: Run formatting style check
      run: ./.github/bin/run-clang-format.sh
